name: RSpec CI

on:
  push:
    branches:
      - 'main'
      - '*-maintenance'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  specs:
    uses: $/.github/workflows/rspec.yml
